version: "3"
services:
  nodejs:
    image: jacksonpires/app-node-dockerizado:v4
    build: .
    ports:
      - 3090
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432
